<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Identity Provider - IdP</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma.min.css">
</head>
<body>
    <section class="hero is-light">
        <div class="hero-body">
            <p class="title">Example Identity Provider - IdP</p>
            <p class="subtitle">
                <?php if (isset($_SESSION['logged']) && $_SESSION['logged']) : ?>
                    Welcome <strong><?=$_SESSION['user']['name']?></strong>
                <?php endif ?>
            </p>
            <div class="is-flex is-align-items-end mt-6">
                <div>
                    <?php if (isset($_SESSION['logged']) && $_SESSION['logged']) : ?>
                        <a class="button is-danger" href="/logout.php">Sign out</a>
                    <?php else: ?>
                        <a class="button is-info" href="/login.php">Sign in</a>
                    <?php endif ?>
                </div>
                <div class="ml-3">
                    <a class="button is-success" href="/info.php">SSO Settings</a>
                </div>
            </div>
        </div>
    </section>
</body>
</html>